### ISSUE TITLE
Docs needed for 'Add NoNewLine switch for Out-String cmdlet'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3077] opened 2018-10-15 21:49 UTC
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/5056

**Comment by matt9ucci** [comment] 2018-10-16 14:36
@sdwheeler The issue is already resolved by #1764

**Comment by sdwheeler** [comment] 2018-10-16 14:45
@matt9ucci Thanks

**Closed by sdwheeler** 2018-10-16 14:45 UTC
Labels: Reference
