### ISSUE TITLE
Docs needed for 'Allow numeric Ids and name of registered code pages in '-Encoding' parameters'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3027] opened 2018-10-15 21:38 UTC
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7636

**Comment by sdwheeler** [comment] 2018-10-26 13:55
This is a duplicate of or related to the following issues:

- #2937
- #2000

**Closed by sdwheeler** 2018-10-26 13:55 UTC
Labels: Area-Cmdlets-Core, Duplicate, Reference
