### ISSUE TITLE
New parameters in Get-Culture cmdlet

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell-Docs#3138] opened 2018-10-18 06:25 UTC
Issue Details
-----------------
Related PR https://github.com/PowerShell/PowerShell/pull/7702

Need to document new parameters in Get-Culture cmdlet:
- Name
- ListAvailable
- NoUserOverrides 

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [ ] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment] 2018-10-18 14:53
This is a duplicate of #3025

**Closed by sdwheeler** 2018-10-18 14:53 UTC
Labels: Duplicate

**Comment by iSazonov** [comment] 2018-10-18 15:29
@sdwheeler NoUserOverrides is not mentioned in #3025
