### ISSUE TITLE
Branch structure need to be clarified in Contributing.md

### ISSUE THREAD

**Issue by vors** [PowerShell/PowerShell-Docs#38] opened 2015-11-04 01:46 UTC
Currently I see 'master' branch and 'live' branch.
It's worth to know branch strategy: where send PRs, when something goes live, etc.

**Comment by joeyaiello** [comment] 2015-11-04 05:12
Agreed. The only reference I currently have in there is this, but it's definitely not enough:
> When you're ready to contribute your documentation, submit a pull request to the *master* branch

We should get something in there ASAP. For posterity, `master` is the current working branch and `live` is a protected branch that gets published into MSDN. 

Also, this isn't set in stone. `live` has to remain the same, but we can have any number of arbitrarily-named branches for separate experiments/projects (and, internally, we can see this content rendered in staging for each branch). 

Does anyone have any opinions on branching?

**Comment by kilasuit** [comment] 2015-11-08 22:08
Just as a suggestive 

Why not rename Live to Master & Master to Dev to conform with other Microsoft Repos as well? examples being the OfficeDevPnP Repos at https://github.com/OfficeDev/

This has become a "typical" naming convention and really helps to reduce potential confusion caused by what is current and what isnt.

Or perhaps just rename Master to Dev??

But as I said just a suggestive. 

:-)

**Comment by DonGill** [comment] 2016-04-06 16:25
I don't this has been resolved yet. @joeyaiello can we sync? We need to lock down on a branching strategy.

**Comment by juanpablojofre** [comment] 2016-05-26 18:11
Closing as resolved/fixed.
Master branch has been renamed Staging.
Live branch remains the same.

**Closed by juanpablojofre** 2016-05-26 18:11 UTC
