### ISSUE TITLE
about_scope, Managing Scope

### ISSUE THREAD

**Issue by udyzr** [PowerShell/PowerShell-Docs#3491] opened 2019-01-02 23:12 UTC
It is about about_scope help article. None to tiny PS-knowledge on my side. I use collection of help articles available under get-help to get familiarized with PS. Following point seems to be presented improperly in about_scope. Section: 'Managing Scope'.

Current text:

> To find the variables that are visible in a particular scope, use the
    Scope parameter of Get-Variable. The visible parameters include global
    parameters, parameters in the parent scope, and parameters in the current
    scope.
>
>    For example, the following command gets the variables that are visible in
    the local scope:
>
>       get-variable -scope local

It seems to should be:

>To find the variables that are visible in a particular scope, use the
    Scope parameter of Get-Variable. The visible **variables** include global
    **variables**, **variables** in the parent scope, and **variables** in the current
    scope.
>
>    For example, the following command gets the variables that are visible in
    the local scope:
>
>        get-variable -scope local

-----------------

Version(s) of document impacted
------------------------------
- [ ] Impacts 6.next document
- [ ] Impacts 6 document
- [x] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [ ] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document
- [x] Other PS versions were not tested cause not available

**Comment by sdwheeler** [comment] 2019-01-03 17:30
This is fixed in the source files and appears correctly on the web site. The problem is that the help files for v5.1 and older are not being built so the changes will not appear in the Get-Help output.

**Closed by sdwheeler** 2019-01-03 17:30 UTC
