### ISSUE TITLE
Correct the information about the default encoding, document BOM behavior with respect to UTF-8 and other Unicode encodings

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#3188] opened 2018-10-26 12:46 UTC
Topics for cmdlets that have an `-Encoding` parameter (`Set-Content`, `Out-File`, ...) need to be updated to reflect that PowerShell _Core_ consistently uses _BOM-less UTF-8_ as the default encoding.
(The current information pertains to _Windows PowerShell_ only, and, as an aside, is in part incorrect - see #1483).

Additionally, given that many cmdlets have an `-Encoding` parameter, it is worth considering introducing a new conceptual topic named, say, `about_character_encodings`, rather than to repeat (too much)  information in each cmdlet's topic.

In addition to an enumeration of the supported encodings and a description, such a new topic could: 

* describe the fundamental differences between the editions with respect to the default encoding in more detail, along with the ramifications.

* provide more guidance, along the lines of the following:

---

A note re the use of a [BOM](https://en.wikipedia.org/wiki/Byte_order_mark) (a.k.a. Unicode signature) with [UTF-8](https://en.wikipedia.org/wiki/UTF-8) and other Unicode encodings:

* In _Windows PowerShell_, `-Encoding utf8` _invariably_ creates a BOM (applies not just to `Set-Content`, but also to other cmdlets that produce file output, such as `Out-File` and `Export-Csv`).

  * Direct use of the .NET framework is required to create BOM-_less_ UTF-8 files. Note that the .NET framework's default encoding has always been BOM-less UTF-8.

* PowerShell _Core_ creates BOM-_less_ UTF-8 files _by default_ (and also when you explicitly use <br>`-Encoding utf8`); you can opt to have a BOM created with `-Encoding utf8BOM`.

For best overall compatibility, BOMs in UTF-8 files should be _avoided_: Unix platforms and Unix-heritage utilities also used on Windows Platforms generally don't know how to handle them.

Similarly, `-Encoding UTF7` should be avoided, because it is not a standard Unicode encoding (and is written _without_ a BOM in both PowerShell editions).

In _both_ PowerShell editions, all other Unicode encodings available with `-Encoding` _do_ create an (encoding-appropriate) BOM: `Unicode` (UTF-16LE), `bigendianunicode` (UTF-16BE), and `utf32` (UTF-32).

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment] 2018-10-26 13:49
This is a duplicate of or related to the following issues:

- #3105
- #3098
- #3076
- #2000
- #1483
- #1101

**Closed by sdwheeler** 2018-10-26 13:49 UTC
Labels: Area-Cmdlets-Core, Duplicate, Reference
