### ISSUE TITLE
Need to expand FileAttributes in Get-ChildItem for v6.1

### ISSUE THREAD

**Issue by rkeithhill** [PowerShell/PowerShell-Docs#2606] opened 2018-06-21 17:08 UTC
Issue Details
-----------------
Long spans of help text that wrap lines do not honor indentation on subsequent lines.  This results in a less than pleasant reading experience. Here is what I'm seeing in 6.1 preview 3 on Windows:

![image](https://user-images.githubusercontent.com/5177512/41734116-4145f77a-7543-11e8-8951-e91c008ecbd7.png)

Compare this to the nicer formatted 5.1 help:

![image](https://user-images.githubusercontent.com/5177512/41734185-7348234c-7543-11e8-8575-7c041c354fed.png)

There is also a typo in the 6.1 Get-ChildItem Description - it says `all child continers` and it should be `all child containers`.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [x] This issue only shows up in selected version of the document

**Comment by DCtheGeek** [comment] 2018-06-21 19:56
Note for whoever picks this up:  Git-ChildItem.md in release-ps61 branch is fine.  Looks like the appearance of a typo was caused by screenwidth/wrapping.  File: https://github.com/PowerShell/PowerShell-Docs/blob/release-ps61/reference/6/Microsoft.PowerShell.Management/Get-ChildItem.md

**Comment by rkeithhill** [comment] 2018-06-21 23:34
I also just noticed that in the 6.1 help the Attributes are not being expanded:
```
<System.Management.Automation.FlagsExpression`1[System.IO.FileAttributes]>
```
like they are in 5.1:
```
{ReadOnly | Hidden | System | Directory | Archive | Device |
    Normal | Temporary | SparseFile | ReparsePoint | Compressed | Offline | NotContentIndexed | Encrypted |
    IntegrityStream | NoScrubData}
```

**Comment by sdwheeler** [comment] 2018-06-25 22:32
@rkeithhill The wrapping problem is a rendering issue in 6.1-preview. The doc source is OK. Can you file an issue in the source code repo for the rendering problem? I am repurposing this issue to update the docs to expand the Attributes.

**Comment by rkeithhill** [comment] 2018-06-25 22:51
Will do.

**Comment by rkeithhill** [comment] 2018-06-25 22:54
And done.

**Comment by alexandair** [comment] 2018-08-02 00:07
@sdwheeler 
Where is the properly rendered help with expended file attributes?

I can see it looking at in-box 5.1 help for Get-ChildItem, but I cannot find a branch that has it properly rendered.

**Comment by sdwheeler** [comment] 2018-08-02 14:36
@alexandair I can't find it either. I don't know when that got changed but we need to revert the syntax blocks back to the version that appears in the currently available updateable help. For v5.1 that is:

```
    Get-ChildItem [[-Filter] <String>] [-Attributes {ReadOnly | Hidden | System | Directory | Archive | Device |
    Normal | Temporary | SparseFile | ReparsePoint | Compressed | Offline | NotContentIndexed | Encrypted |
    IntegrityStream | NoScrubData}] [-Depth <UInt32>] [-Directory] [-Exclude <String[]>] [-File] [-Force] [-Hidden]
    [-Include <String[]>] -LiteralPath <String[]> [-Name] [-ReadOnly] [-Recurse] [-System] [-UseTransaction]
    [<CommonParameters>]

    Get-ChildItem [[-Path] <String[]>] [[-Filter] <String>] [-Attributes {ReadOnly | Hidden | System | Directory |
    Archive | Device | Normal | Temporary | SparseFile | ReparsePoint | Compressed | Offline | NotContentIndexed |
    Encrypted | IntegrityStream | NoScrubData}] [-Depth <UInt32>] [-Directory] [-Exclude <String[]>] [-File] [-Force]
    [-Hidden] [-Include <String[]>] [-Name] [-ReadOnly] [-Recurse] [-System] [-UseTransaction] [<CommonParameters>]

    Get-ChildItem [-Attributes <FileAttributes]>] [-Directory] [-File] [-Force] [-Hidden] [-ReadOnly] [-System]
    [-UseTransaction] [<CommonParameters>]
```

**Comment by alexandair** [comment] 2018-08-03 11:48
@sdwheeler 
You can close it and remove "Documentation needed" label.
#2765 has a fix.

**Closed** 2018-08-03 13:15 UTC
Labels: Pri-High, Reference, vNext-Docs
