### ISSUE TITLE
Example 1 isn't supported in PowerShell 6

### ISSUE THREAD

**Issue by justindbelanger** [PowerShell/PowerShell-Docs#3371] opened 2018-12-03 17:12 UTC
Hi,
The first example for Set-PSReadlineOption shows the use of the -TokenKind argument, which doesn't appear to be supported in PowerShell 6. Earlier in the document it does correctly show the -Colors argument in the list of supported args, so could the example be updated to demonstrate how to use that, instead?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 801e7046-e140-f89e-6f4e-700c9503107c
* Version Independent ID: 18945940-0df3-1027-612f-2adf6291d22d
* Content: [Set-PSReadlineOption (PSReadLine)](https://docs.microsoft.com/en-us/powershell/module/psreadline/set-psreadlineoption?view=powershell-6#examples)
* Content Source: [reference/6/PSReadLine/Set-PSReadlineOption.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/PSReadLine/Set-PSReadlineOption.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by doctordns** [comment] 2018-12-03 17:40
The issue here is that the version of PSReadLine in PS6 is updated. To get the updated documentation you need to go to [PSReadLInes GitHub home page. ](https://github.com/lzybkr/PSReadLine).

You also would find this issue if you are using the latest editions of Windows 10 (eg 1809 or later). This is because both PWSH 6 and the latest versions of WIndows ships with a later version of PSReadline.

**Comment by sdwheeler** [comment] 2018-12-03 22:18
@justindbelanger This is a duplicate of #3185. @doctordns is correct about the change to V2 of PSReadline. We are working on how to update this content appropriately.

**Closed by sdwheeler** 2018-12-03 22:18 UTC
Labels: Area-PSReadline, Duplicate, Reference
