### ISSUE TITLE
Need an about_Error_Handling topic

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/PowerShell-Docs#1424] opened 2017-06-30 15:16 UTC
Issue Details
-----------------
The other day I went to show a customer documentation for PowerShell error handling. I always assumed it was there. Guess not. We do not have an overview about topic for PowerShell error handling. How did we miss this over the last ten years?

Instead, I had to give them these links:
https://blogs.msdn.microsoft.com/kebab/2013/06/09/an-introduction-to-error-handling-in-powershell/
The Big Book of PowerShell Error Handling
https://powershell.org/ebooks/
https://www.gitbook.com/book/devops-collective-inc/the-big-book-of-powershell-error-handling/details

The content should address terminating vs non-terminating errors, handling each kind of error, how to identify the exception class name to put into a trap or catch, preference variables, common error handling script conventions, $error object, etc.

Some parts of this may be scattered throughout other parts of the help system or cmdlets, but it is incomplete. Need an overview topic from the top-down.

Then link to these:
about_Trap
about_Try_Catch_Finally
about_Throw
about_CommonParameters
about_Preference_Variables

Version(s) of document impacted
------------------------------
- [x] Impacts 6 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by zjalexander** [comment] 2017-08-30 22:01
Duplicate of #1583 .

**Closed by zjalexander** 2017-08-30 22:01 UTC
