### ISSUE TITLE
Compress-Archive help topic is missing description for the -Force parameter

### ISSUE THREAD

**Issue by alexandair** [PowerShell/PowerShell-Docs#845] opened 2016-11-20 01:09 UTC
Compress-Archive help topic is missing description for the -Force parameter.
There is a placeholder instead.

**Comment by juanpablojofre** [comment] 2016-12-16 18:38
@alexandair,
Yes this is another case of a wider issue that I'm working on in #889.
I'm closing this as a duplicate of #889.

**Closed by juanpablojofre** 2016-12-16 18:38 UTC
