### ISSUE TITLE
Optional Parameter -DestinationPath is required?

### ISSUE THREAD

**Issue by gakera** [PowerShell/PowerShell-Docs#3380] opened 2018-12-05 17:41 UTC
...um ok, not sure if this is as it should be?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b551b9cd-f608-082f-7cbd-a98e417f2c9a
* Version Independent ID: 0a5e7f63-6363-af13-a2ca-79190f459d40
* Content: [Expand-Archive (Microsoft.PowerShell.Archive)](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.archive/Expand-Archive?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Archive/Expand-Archive.md)
* Product: **powershell**
* GitHub Login: @joeyaiello
* Microsoft Alias: **jaiello**

**Comment by sdwheeler** [comment] 2018-12-05 17:58
This is a duplicate of #3369 and was addressed in #3372. But the change has not gone live yet.

**Closed by sdwheeler** 2018-12-05 17:58 UTC
