### ISSUE TITLE
OPS Highlighting doesn't understand block comments

### ISSUE THREAD

**Issue by ArieHein** [PowerShell/PowerShell-Docs#319] opened 2016-04-27 00:22 UTC
https://msdn.microsoft.com/en-us/powershell/wmf/dsc_classbasedresource

Line 48 of the main example has an extra ' that breaks the code

**Comment by HemantMahawar** [comment] 2016-04-29 23:22
Thank you @ArieHein  for reporting this issue. Fixed with #334

**Comment by vors** [comment] 2016-04-29 23:30
Extra `'` doesn't break the code, it only breaks OPS highlighting for PowerShell.
We should fix the highlighting engine that OPS uses.

**Comment by HemantMahawar** [comment] 2016-04-29 23:44
@eslesar @DonGill ... can we get the tooling fixed?

**Comment by vors** [comment] 2016-04-29 23:52
```powershell
<# 
this is block comment 
#>
```

**Comment by eslesar** [comment] 2016-05-12 18:13
Sent feature request to OPS team.

**Comment by HemantMahawar** [comment] 2016-05-12 18:25
@eslesar This should remain open till OPS team delivers this feature ... cc @joeyaiello @vors

**Comment by HemantMahawar** [comment] 2016-07-11 18:00
@saldana Any idea when will this be fixed? ... cc @DonGill @joeyaiello

**Comment by saldana** [comment] 2016-07-11 19:20
@HemantMahawar, I get a 404 when accessing https://msdn.microsoft.com/en-us/powershell/wmf/dsc_classbasedresource. I am not sure what the issue is or if this has been reported to our team in TFS. What is the bug number?

**Comment by HemantMahawar** [comment] 2016-07-11 19:57
Content has been moved to https://msdn.microsoft.com/powershell/dsc/authoringresourceclass.
Look at the "complete file" section https://msdn.microsoft.com/powershell/dsc/authoringresourceclass#the-complete-file , specifically in the block comment after `[string] $SourcePath`

**Comment by saldana** [comment] 2016-07-12 23:41
Thanks. @DonGill, can you guys enter a bug for our team to fix this problem? Thanks.

**Comment by vors** [comment] 2016-07-13 20:00
cc @sankethka

**Comment by sdwheeler** [comment] 2017-08-16 22:32
Now that the documentation has been migrated from MSDN to docs.microsoft.com, this is no longer an issue.

**Closed by sdwheeler** 2017-08-16 22:32 UTC
Labels: Issue-Bug, triaged
