### ISSUE TITLE
NO HELP for New-FileCatalog

### ISSUE THREAD

**Issue by Jaykul** [PowerShell/PowerShell-Docs#1441] opened 2017-07-14 04:08 UTC
What the title says. `Get-Help New-FileCatalog -online` takes you to [this wrong page](https://technet.microsoft.com/library/cc732148.aspx), but looking it up online led me to a basically blank [page on msdn](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.security/new-filecatalog) and it's [source here](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Security/New-FileCatalog.md).

**Comment by joeyaiello** [comment] 2017-08-08 23:43
Good starting point for us to port from: https://docs.microsoft.com/en-us/powershell/wmf/5.1/scenarios-features#catalog-cmdlets

**Comment by joeyaiello** [comment] 2017-08-08 23:56
This is actually a dupe of #652

**Closed by joeyaiello** 2017-08-08 23:56 UTC
Labels: Area-Cmdlets, Review - Waiting on PowerShell Team
