### ISSUE TITLE
There are two versions of this page under https://docs.microsoft.com/en-us/powershell/module/ -- this page is the older version

### ISSUE THREAD

**Issue by ScottEP** [PowerShell/PowerShell-Docs#3596] opened 2019-01-23 13:28 UTC
This page (https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psreadline?view=powershell-6) was last edited on 01/03/2018.

There is another page for about_PSReadline (https://docs.microsoft.com/en-us/powershell/module/psreadline/about/about_psreadline?view=powershell-6), last edited on 12/07/2018, that seems to be more up to date, content-wise.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 84967149-2769-0a40-fbed-995575c189dd
* Version Independent ID: b2dbc749-9716-5d35-3c81-a6a708735439
* Content: [about_PSReadline](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_psreadline?view=powershell-6)
* Content Source: [reference/6/Microsoft.PowerShell.Core/About/about_psreadline.md](https://github.com/PowerShell/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_psreadline.md)
* Product: **powershell**
* GitHub Login: @SteveL-MSFT
* Microsoft Alias: **slee**

**Comment by sdwheeler** [comment] 2019-01-23 18:06
Duplicate of #3596

**Closed by sdwheeler** 2019-01-23 18:06 UTC
Labels: Area-PSReadline, Duplicate
