### ISSUE TITLE
Docs needed for 'Remove BuildVersion from  $PSVersionTable'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3099] opened 2018-10-15 21:54 UTC
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/3877

**Comment by matt9ucci** [comment] 2018-10-19 11:49
@sdwheeler It would be better to merge the issue and #2229. Both are related to GitCommitId and BuildVersion.

**Comment by sdwheeler** [comment] 2018-10-19 13:10
Duplicate of #2229

**Closed by sdwheeler** 2018-10-19 13:10 UTC
Labels: Duplicate, Reference
