### ISSUE TITLE
Get-Help About* can't display synopsis

### ISSUE THREAD

**Issue by juneb** [PowerShell/PowerShell-Docs#658] opened 2016-10-04 00:59 UTC
In PowerShell 5.0, the About topic have an extra line at the top that repeats the topic name. As a result, when you run Get-Help about_*, the display, which gets Line 5 is grabbing 'SHORT DESCRIPTION' instead of the short description on line 5.

We really need to convert About topics to XML/JSON objects so your tools don't break the features.

`
about_Aliases    #<--------- this is the extra line.
TOPIC
    about_aliases

SHORT DESCRIPTION
    Describes how to use alternate names for cmdlets and commands in Windows
    PowerShell. 

LONG DESCRIPTION
`

![screenshot 2016-10-03 18 33 08](https://cloud.githubusercontent.com/assets/2954883/19059144/d612a60a-899a-11e6-86d0-bfd49cf9cc7f.png)

**Comment by juanpablojofre** [comment] 2016-10-05 17:22
@June, I'll look into this...

Can you tell me why is it that your PS version says 6.0 in the screenshot provided?

**Comment by juneb** [comment] 2016-10-05 17:58
Because I was using 6.0. Here's the same thing in 5.1. 6.0 doesn't have help files in its $pshome\en-US, so it must be using the 5.0 $pshome\en-US files. 
![screenshot 2016-10-05 11 57 11](https://cloud.githubusercontent.com/assets/2954883/19125112/13cdbb98-8af3-11e6-91ec-07705a9d5e7f.png)

**Comment by NReilingh** [comment] 2016-12-18 16:42
As of 12/18/2016... well, THIS is awkward @juanpablojofre :-) (5.1.14393.576)

![screen shot 2016-12-18 at 11 37 31 am](https://cloud.githubusercontent.com/assets/2458645/21294896/7c4a6ab0-c516-11e6-8397-a688252a111c.png)

Where would we expect to find it documented how Get-Help produces the Synopsis column from .help.txt files? Seems like it's always just "Line 5."

**Comment by nightroman** [comment] 2016-12-18 17:56
A remark about [Invoke-Build #40](https://gutithub.com/nightroman/Invoke-Build/issues/40). The symptoms look the same but the reason is the empty first line before TOPIC. In other words, if the file starts with a blank line then there is an issue.

**Comment by zjalexander** [comment] 2017-02-24 17:39
This should have been fixed a while ago - @juneb can we close this issue or is there still a case I need to investigate?

**Comment by SAPIENTechnologies** [comment] 2017-02-24 22:08
Looks great. In 6.0.0.16, the only About topic that's off by one line is about_PSReadline.

Here's the cause:
```
about_PSReadline        <---- Extraneous line from one of the tools. 
TOPIC
    about_PSReadline

SHORT DESCRIPTION
```

**Comment by juneb** [comment] 2017-02-24 22:09
Looks great. In 6.0.0.16, the only About topic that's off by one line is about_PSReadline.

Here's the cause:

about_PSReadline        <---- Extraneous line from one of the tools. 
TOPIC
    about_PSReadline

SHORT DESCRIPTION

**Comment by zjalexander** [comment] 2017-02-24 22:14
looks like that issue is fixed in the psreadline repo, just need to make sure its incorporated into the downloadable help pipeline #1073

**Closed by zjalexander** 2017-02-24 22:14 UTC
