### ISSUE TITLE
about_Arrays, array methods

### ISSUE THREAD

**Issue by TheIncorrigible1** [PowerShell/PowerShell-Docs#2444] opened 2018-05-17 23:21 UTC
Issue Details
-----------------
Could we as a community get better documentation on the `Where` and `ForEach` array filters/methods?  I only knew they existed from reading the v4 release notes and have randomly stumbled across more interesting use-cases that I can't find any documentation for (such as `Where` having "modes" you can pass to it such as split and `ForEach` being able to directly operate on the current item without directly referencing in the case of typecasting).  There's also the matter that unlike their pipeline counterparts, they load the entire array into memory to be worked on at once.

Additionally, this is mentioned in v3, but wasn't introduced until v4.  In this case, the reference to these methods should be removed.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [x] Impacts 4.0 document
- [x] Impacts 3.0 document

**Comment by doctordns** [comment] 2018-05-18 09:37
The obvious answer to this question is YES. You are free to click the Edit buttons to get from the article to GitHub to the GitHub editor. Edit away and issue a Pull Request. 

If you want help in doing this - feel free to reach out. I'd be happy to help you!

**Comment by TheIncorrigible1** [comment] 2018-05-25 12:52
@doctordns Unfortunately I don't understand them well enough nor where to search for the source to document them myself.

**Comment by doctordns** [comment] 2018-05-25 13:11
So send me mail and I'd be happy to help.

**Comment by sdwheeler** [comment] 2018-06-06 17:50
This is a duplicate of #2307. Will track update efforts in that issue.

**Closed by sdwheeler** 2018-06-06 17:50 UTC
Labels: duplicate
