### ISSUE TITLE
Add rationale for why Write-Information output is not "INFO: "-prefixed to the help topic

### ISSUE THREAD

**Issue by mklement0** [PowerShell/PowerShell-Docs#2483] opened 2018-05-30 21:24 UTC
A follow-up from https://github.com/PowerShell/PowerShell/issues/6951:

`Write-Information` output does _not_ use an `INFO: ` prefix when printing its output to the _console_ (assuming it is enabled with a `Continue` preference-variable / common-parameter value). This prefix currently does show up in _transcripts_, but that inconsistency will be fixed.

Users may be surprised at the absence of the prefix, given that the cmdlets targeting other non-success streams - `Write-Verbose`, `Write-Warning`, and `Write-Debug` - all use an analogous prefix when printing to the console (`VERBOSE: `, ...), so as to make it easier to distinguish data (success) output from output to other streams.

However, https://github.com/PowerShell/PowerShell/issues/6951#issuecomment-393290377 explains that omitting the prefix was a deliberate decision so as to reduce visual clutter, so this rationale should be added to the help topic.

Version(s) of document impacted
------------------------------
- [x] Impacts 6.1 document
- [x] Impacts 6.0 document
- [x] Impacts 5.1 document
- [x] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [x] The documented feature was introduced in selected version of PowerShell
- [ ] This issue only shows up in selected version of the document

**Comment by sdwheeler** [comment] 2018-06-06 17:57
This is by design.

**Comment by mklement0** [comment] 2018-06-06 18:01
@sdwheeler: Yes, but because the design may be _surprising_ (see the original post), my suggestion was to _add a design note_ to the docs, so users _know_ that it is by design, and don't question the behavior.

**Comment by mklement0** [comment] 2018-06-06 18:03
@sdwheeler: To put it differently: that the behavior described by the issue is indeed by design was the very starting point.

**Comment by sdwheeler** [comment] 2018-06-07 02:11
@mklement0 This would be extremely low priority. It would help if you could submit a PR with the appropriate change.

**Comment by bobbytreed** [comment] 2018-06-27 10:06
Closed by #2619

**Closed by bobbytreed** 2018-06-27 10:06 UTC
