### ISSUE TITLE
Docs needed for 'Add %F option to Get-Date -UFormat'

### ISSUE THREAD

**Issue by joeyaiello** [PowerShell/PowerShell-Docs#3029] opened 2018-10-15 21:38 UTC
This issue was generated because an issue in the
[PowerShell/PowerShell](https://github.com/powershell/powershell) repository had an issue marked
as `Documentation Needed` and should instead be tracked here in PowerShell-Docs. 

The pull request or issue that contains this is located at https://github.com/PowerShell/PowerShell/pull/7630

**Comment by matt9ucci** [comment] 2018-10-16 15:47
@sdwheeler The issue is already resolved by #2959

**Comment by sdwheeler** [comment] 2018-10-16 15:48
@matt9ucci Thanks

**Closed by sdwheeler** 2018-10-16 15:48 UTC
Labels: Reference
